name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar Poetry
        run: pip install poetry        # ← mudança aqui

      - name: Instalar dependências
        run: poetry install --no-root --no-interaction

      - name: Rodar testes
        run: poetry run pytest